server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:pedidos;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
      acks: all
      properties:
        enable.idempotence: true
        linger.ms: 5
        schema.registry.url: http://localhost:8081
    consumer:
      group-id: faturamento
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 50
      properties:
        max.poll.interval.ms: 300000
        session.timeout.ms: 45000
        schema.registry.url: http://localhost:8081
        json.value.type: com.trilhas.kafka.lab.PedidoCriado
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer
    listener:
      ack-mode: manual
      concurrency: 3

lab:
  topic: pedidos.criados
  partitions: 3
  analytics-group: analytics
