import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  devIndicators: false,
  async redirects() {
    return [
      {
        source: "/:path*",
        has: [{ type: "host", value: "trilhas-backend.vercel.app" }],
        destination: "https://learning.codetoscale.dev/:path*",
        permanent: true,
      },
      // Old category hubs → new EN hubs
      { source: "/category/apache-kafka", destination: "/category/system-design", permanent: true },
      { source: "/category/apache-kafka/:path*", destination: "/category/system-design/:path*", permanent: true },
      { source: "/category/sistemas-distribuidos", destination: "/category/system-design", permanent: true },
      { source: "/category/sistemas-distribuidos/:path*", destination: "/category/system-design/:path*", permanent: true },
      { source: "/category/design-patterns", destination: "/category/system-design", permanent: true },
      { source: "/category/design-patterns/:path*", destination: "/category/system-design/:path*", permanent: true },
      { source: "/category/data-modeling", destination: "/category/system-design", permanent: true },
      { source: "/category/data-modeling/:path*", destination: "/category/system-design/:path*", permanent: true },
      { source: "/category/concorrencia", destination: "/category/system-design", permanent: true },
      { source: "/category/concorrencia/:path*", destination: "/category/system-design/:path*", permanent: true },
      { source: "/category/clean-code", destination: "/category/code", permanent: true },
      { source: "/category/clean-code/:path*", destination: "/category/code/:path*", permanent: true },

      // Retired SD article slugs → category hub (or Kafka deep dive)
      { source: "/category/system-design/mapa-e-fronteiras", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/boundaries-and-map", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/staff-e-referencia", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/staff-and-reference", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/distribuido", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/decomposition-and-data", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/escala-e-resiliencia", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/scale-and-resilience", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/propriedades-de-dados", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/data-properties", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/blocos-e-padroes", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/blocks-and-patterns", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/system-design-pratica", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/system-design-practice", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/sync-vs-async", destination: "/category/system-design", permanent: true },
      { source: "/category/system-design/fundamentos", destination: "/category/system-design/kafka", permanent: true },
      { source: "/category/system-design/anatomia", destination: "/category/system-design/kafka", permanent: true },
      { source: "/category/system-design/cluster", destination: "/category/system-design/kafka", permanent: true },
      { source: "/category/system-design/dinamica", destination: "/category/system-design/kafka", permanent: true },
      { source: "/category/system-design/garantias", destination: "/category/system-design/kafka", permanent: true },
      { source: "/category/system-design/pratica", destination: "/category/system-design/kafka", permanent: true },
      { source: "/category/system-design/sintese", destination: "/category/system-design/kafka", permanent: true },
      { source: "/category/system-design/kafka-fundamentals", destination: "/category/system-design/kafka", permanent: true },
      { source: "/category/system-design/kafka-anatomy", destination: "/category/system-design/kafka", permanent: true },
      { source: "/category/system-design/kafka-cluster", destination: "/category/system-design/kafka", permanent: true },
      { source: "/category/system-design/kafka-lifecycle", destination: "/category/system-design/kafka", permanent: true },
      { source: "/category/system-design/kafka-guarantees", destination: "/category/system-design/kafka", permanent: true },
      { source: "/category/system-design/kafka-in-practice", destination: "/category/system-design/kafka", permanent: true },
      { source: "/category/system-design/kafka-synthesis", destination: "/category/system-design/kafka", permanent: true },
      { source: "/category/code/nomes-e-funcoes", destination: "/category/code", permanent: true },
      { source: "/category/code/names-and-functions", destination: "/category/code", permanent: true },

      // Legacy track homes
      { source: "/kafka", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura", destination: "/category/system-design", permanent: true },

      // Kafka lesson → M5 Kafka deep dive
      { source: "/kafka/fundamentos", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/anatomia", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/cluster", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/dinamica", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/garantias", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/pratica", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/sintese", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/simulador", destination: "/category/system-design/quiz", permanent: true },
      { source: "/kafka/modelo-mental", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/evento", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/topico", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/particao", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/offset", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/key", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/broker", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/isr", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/produtor", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/consumidor", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/rebalance", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/retencao", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/operacao", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/schema", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/outbox", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/spring", destination: "/category/system-design/kafka", permanent: true },
      { source: "/kafka/tech-lead", destination: "/category/system-design/kafka", permanent: true },

      // Arquitetura lesson → SD hub
      { source: "/arquitetura/fundamentos", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/mapa", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/sistema", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/propriedades", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/latencia", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/disponibilidade", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/cap", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/acid", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/cache", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/replicacao", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/indice", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/blocos", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/monolito", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/sincrono", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/operacao", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/escala", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/resiliencia", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/distribuido", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/decomposicao", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/dados", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/observabilidade", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/pratica", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/system-design", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/catalogo", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/sintese", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/staff", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/referencia", destination: "/category/system-design", permanent: true },
      { source: "/arquitetura/simulador", destination: "/category/system-design/quiz", permanent: true },
    ];
  },
};

export default nextConfig;
